# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfaz.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!
from PyQt4 import QtCore, QtGui


try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(772, 512)
        self.leerArchivoDeTexto = QtGui.QPushButton(Dialog)
        self.leerArchivoDeTexto.setEnabled(True)
        self.leerArchivoDeTexto.setGeometry(QtCore.QRect(400, 420, 151, 41))
        self.leerArchivoDeTexto.setObjectName(_fromUtf8("leerArchivoDeTexto"))
        self.salir = QtGui.QPushButton(Dialog)
        self.salir.setGeometry(QtCore.QRect(590, 420, 151, 41))
        self.salir.setObjectName(_fromUtf8("salir"))
        self.b0_0 = QtGui.QPushButton(Dialog)
        self.b0_0.setGeometry(QtCore.QRect(30, 20, 81, 61))
        self.b0_0.setIconSize(QtCore.QSize(55, 55))
        self.b0_0.setObjectName(_fromUtf8("b0_0"))
        self.b1_0 = QtGui.QPushButton(Dialog)
        self.b1_0.setGeometry(QtCore.QRect(120, 20, 81, 61))
        self.b1_0.setIconSize(QtCore.QSize(55, 55))
        self.b1_0.setObjectName(_fromUtf8("b1_0"))
        self.b2_0 = QtGui.QPushButton(Dialog)
        self.b2_0.setGeometry(QtCore.QRect(210, 20, 81, 61))
        self.b2_0.setIconSize(QtCore.QSize(55, 55))
        self.b2_0.setObjectName(_fromUtf8("b2_0"))
        self.b3_0 = QtGui.QPushButton(Dialog)
        self.b3_0.setGeometry(QtCore.QRect(300, 20, 81, 61))
        self.b3_0.setIconSize(QtCore.QSize(55, 55))
        self.b3_0.setObjectName(_fromUtf8("b3_0"))
        self.b4_0 = QtGui.QPushButton(Dialog)
        self.b4_0.setGeometry(QtCore.QRect(390, 20, 81, 61))
        self.b4_0.setIconSize(QtCore.QSize(55, 55))
        self.b4_0.setObjectName(_fromUtf8("b4_0"))
        self.b5_0 = QtGui.QPushButton(Dialog)
        self.b5_0.setGeometry(QtCore.QRect(480, 20, 81, 61))
        self.b5_0.setIconSize(QtCore.QSize(55, 55))
        self.b5_0.setObjectName(_fromUtf8("b5_0"))
        self.b7_0 = QtGui.QPushButton(Dialog)
        self.b7_0.setGeometry(QtCore.QRect(660, 20, 81, 61))
        self.b7_0.setIconSize(QtCore.QSize(55, 55))
        self.b7_0.setObjectName(_fromUtf8("b7_0"))
        self.b6_0 = QtGui.QPushButton(Dialog)
        self.b6_0.setGeometry(QtCore.QRect(570, 20, 81, 61))
        self.b6_0.setIconSize(QtCore.QSize(55, 55))
        self.b6_0.setObjectName(_fromUtf8("b6_0"))
        self.b7_1 = QtGui.QPushButton(Dialog)
        self.b7_1.setGeometry(QtCore.QRect(660, 80, 81, 61))
        self.b7_1.setIconSize(QtCore.QSize(55, 55))
        self.b7_1.setObjectName(_fromUtf8("b7_1"))
        self.b4_1 = QtGui.QPushButton(Dialog)
        self.b4_1.setGeometry(QtCore.QRect(390, 80, 81, 61))
        self.b4_1.setIconSize(QtCore.QSize(55, 55))
        self.b4_1.setText(_fromUtf8(""))
        self.b4_1.setObjectName(_fromUtf8("b4_1"))
        self.b1_1 = QtGui.QPushButton(Dialog)
        self.b1_1.setGeometry(QtCore.QRect(120, 80, 81, 61))
        self.b1_1.setIconSize(QtCore.QSize(55, 55))
        self.b1_1.setText(_fromUtf8(""))
        self.b1_1.setObjectName(_fromUtf8("b1_1"))
        self.b5_1 = QtGui.QPushButton(Dialog)
        self.b5_1.setGeometry(QtCore.QRect(480, 80, 81, 61))
        self.b5_1.setIconSize(QtCore.QSize(55, 55))
        self.b5_1.setText(_fromUtf8(""))
        self.b5_1.setObjectName(_fromUtf8("b5_1"))
        self.b6_1 = QtGui.QPushButton(Dialog)
        self.b6_1.setGeometry(QtCore.QRect(570, 80, 81, 61))
        self.b6_1.setIconSize(QtCore.QSize(55, 55))
        self.b6_1.setText(_fromUtf8(""))
        self.b6_1.setObjectName(_fromUtf8("b6_1"))
        self.b0_1 = QtGui.QPushButton(Dialog)
        self.b0_1.setGeometry(QtCore.QRect(30, 80, 81, 61))
        self.b0_1.setIconSize(QtCore.QSize(55, 55))
        self.b0_1.setObjectName(_fromUtf8("b0_1"))
        self.b2_1 = QtGui.QPushButton(Dialog)
        self.b2_1.setGeometry(QtCore.QRect(210, 80, 81, 61))
        self.b2_1.setIconSize(QtCore.QSize(55, 55))
        self.b2_1.setText(_fromUtf8(""))
        self.b2_1.setObjectName(_fromUtf8("b2_1"))
        self.b3_1 = QtGui.QPushButton(Dialog)
        self.b3_1.setGeometry(QtCore.QRect(300, 80, 81, 61))
        self.b3_1.setIconSize(QtCore.QSize(55, 55))
        self.b3_1.setText(_fromUtf8(""))
        self.b3_1.setObjectName(_fromUtf8("b3_1"))
        self.b7_2 = QtGui.QPushButton(Dialog)
        self.b7_2.setGeometry(QtCore.QRect(660, 140, 81, 61))
        self.b7_2.setIconSize(QtCore.QSize(55, 55))
        self.b7_2.setObjectName(_fromUtf8("b7_2"))
        self.b4_2 = QtGui.QPushButton(Dialog)
        self.b4_2.setGeometry(QtCore.QRect(390, 140, 81, 61))
        self.b4_2.setIconSize(QtCore.QSize(55, 55))
        self.b4_2.setText(_fromUtf8(""))
        self.b4_2.setObjectName(_fromUtf8("b4_2"))
        self.b1_2 = QtGui.QPushButton(Dialog)
        self.b1_2.setGeometry(QtCore.QRect(120, 140, 81, 61))
        self.b1_2.setIconSize(QtCore.QSize(55, 55))
        self.b1_2.setText(_fromUtf8(""))
        self.b1_2.setObjectName(_fromUtf8("b1_2"))
        self.b5_2 = QtGui.QPushButton(Dialog)
        self.b5_2.setGeometry(QtCore.QRect(480, 140, 81, 61))
        self.b5_2.setIconSize(QtCore.QSize(55, 55))
        self.b5_2.setText(_fromUtf8(""))
        self.b5_2.setObjectName(_fromUtf8("b5_2"))
        self.b6_2 = QtGui.QPushButton(Dialog)
        self.b6_2.setGeometry(QtCore.QRect(570, 140, 81, 61))
        self.b6_2.setIconSize(QtCore.QSize(55, 55))
        self.b6_2.setText(_fromUtf8(""))
        self.b6_2.setObjectName(_fromUtf8("b6_2"))
        self.b0_2 = QtGui.QPushButton(Dialog)
        self.b0_2.setGeometry(QtCore.QRect(30, 140, 81, 61))
        self.b0_2.setIconSize(QtCore.QSize(55, 55))
        self.b0_2.setObjectName(_fromUtf8("b0_2"))
        self.b2_2 = QtGui.QPushButton(Dialog)
        self.b2_2.setGeometry(QtCore.QRect(210, 140, 81, 61))
        self.b2_2.setIconSize(QtCore.QSize(55, 55))
        self.b2_2.setText(_fromUtf8(""))
        self.b2_2.setObjectName(_fromUtf8("b2_2"))
        self.b3_2 = QtGui.QPushButton(Dialog)
        self.b3_2.setGeometry(QtCore.QRect(300, 140, 81, 61))
        self.b3_2.setIconSize(QtCore.QSize(55, 55))
        self.b3_2.setText(_fromUtf8(""))
        self.b3_2.setObjectName(_fromUtf8("b3_2"))
        self.b1_3 = QtGui.QPushButton(Dialog)
        self.b1_3.setGeometry(QtCore.QRect(120, 200, 81, 61))
        self.b1_3.setIconSize(QtCore.QSize(55, 55))
        self.b1_3.setText(_fromUtf8(""))
        self.b1_3.setObjectName(_fromUtf8("b1_3"))
        self.b4_4 = QtGui.QPushButton(Dialog)
        self.b4_4.setGeometry(QtCore.QRect(390, 260, 81, 61))
        self.b4_4.setIconSize(QtCore.QSize(55, 55))
        self.b4_4.setText(_fromUtf8(""))
        self.b4_4.setObjectName(_fromUtf8("b4_4"))
        self.b4_3 = QtGui.QPushButton(Dialog)
        self.b4_3.setGeometry(QtCore.QRect(390, 200, 81, 61))
        self.b4_3.setIconSize(QtCore.QSize(55, 55))
        self.b4_3.setText(_fromUtf8(""))
        self.b4_3.setObjectName(_fromUtf8("b4_3"))
        self.b1_4 = QtGui.QPushButton(Dialog)
        self.b1_4.setGeometry(QtCore.QRect(120, 260, 81, 61))
        self.b1_4.setIconSize(QtCore.QSize(55, 55))
        self.b1_4.setText(_fromUtf8(""))
        self.b1_4.setObjectName(_fromUtf8("b1_4"))
        self.b6_3 = QtGui.QPushButton(Dialog)
        self.b6_3.setGeometry(QtCore.QRect(570, 200, 81, 61))
        self.b6_3.setIconSize(QtCore.QSize(55, 55))
        self.b6_3.setText(_fromUtf8(""))
        self.b6_3.setObjectName(_fromUtf8("b6_3"))
        self.b3_5 = QtGui.QPushButton(Dialog)
        self.b3_5.setGeometry(QtCore.QRect(300, 320, 81, 61))
        self.b3_5.setIconSize(QtCore.QSize(55, 55))
        self.b3_5.setObjectName(_fromUtf8("b3_5"))
        self.b3_3 = QtGui.QPushButton(Dialog)
        self.b3_3.setGeometry(QtCore.QRect(300, 200, 81, 61))
        self.b3_3.setIconSize(QtCore.QSize(55, 55))
        self.b3_3.setText(_fromUtf8(""))
        self.b3_3.setObjectName(_fromUtf8("b3_3"))
        self.b0_3 = QtGui.QPushButton(Dialog)
        self.b0_3.setGeometry(QtCore.QRect(30, 200, 81, 61))
        self.b0_3.setIconSize(QtCore.QSize(55, 55))
        self.b0_3.setObjectName(_fromUtf8("b0_3"))
        self.b2_5 = QtGui.QPushButton(Dialog)
        self.b2_5.setGeometry(QtCore.QRect(210, 320, 81, 61))
        self.b2_5.setIconSize(QtCore.QSize(55, 55))
        self.b2_5.setObjectName(_fromUtf8("b2_5"))
        self.b2_3 = QtGui.QPushButton(Dialog)
        self.b2_3.setGeometry(QtCore.QRect(210, 200, 81, 61))
        self.b2_3.setIconSize(QtCore.QSize(55, 55))
        self.b2_3.setText(_fromUtf8(""))
        self.b2_3.setObjectName(_fromUtf8("b2_3"))
        self.b6_5 = QtGui.QPushButton(Dialog)
        self.b6_5.setGeometry(QtCore.QRect(570, 320, 81, 61))
        self.b6_5.setIconSize(QtCore.QSize(55, 55))
        self.b6_5.setObjectName(_fromUtf8("b6_5"))
        self.b0_4 = QtGui.QPushButton(Dialog)
        self.b0_4.setGeometry(QtCore.QRect(30, 260, 81, 61))
        self.b0_4.setIconSize(QtCore.QSize(55, 55))
        self.b0_4.setObjectName(_fromUtf8("b0_4"))
        self.b7_5 = QtGui.QPushButton(Dialog)
        self.b7_5.setGeometry(QtCore.QRect(660, 320, 81, 61))
        self.b7_5.setIconSize(QtCore.QSize(55, 55))
        self.b7_5.setObjectName(_fromUtf8("b7_5"))
        self.b7_4 = QtGui.QPushButton(Dialog)
        self.b7_4.setGeometry(QtCore.QRect(660, 260, 81, 61))
        self.b7_4.setIconSize(QtCore.QSize(55, 55))
        self.b7_4.setObjectName(_fromUtf8("b7_4"))
        self.b3_4 = QtGui.QPushButton(Dialog)
        self.b3_4.setGeometry(QtCore.QRect(300, 260, 81, 61))
        self.b3_4.setIconSize(QtCore.QSize(55, 55))
        self.b3_4.setText(_fromUtf8(""))
        self.b3_4.setObjectName(_fromUtf8("b3_4"))
        self.b1_5 = QtGui.QPushButton(Dialog)
        self.b1_5.setGeometry(QtCore.QRect(120, 320, 81, 61))
        self.b1_5.setIconSize(QtCore.QSize(55, 55))
        self.b1_5.setObjectName(_fromUtf8("b1_5"))
        self.b5_4 = QtGui.QPushButton(Dialog)
        self.b5_4.setGeometry(QtCore.QRect(480, 260, 81, 61))
        self.b5_4.setIconSize(QtCore.QSize(55, 55))
        self.b5_4.setText(_fromUtf8(""))
        self.b5_4.setObjectName(_fromUtf8("b5_4"))
        self.b0_5 = QtGui.QPushButton(Dialog)
        self.b0_5.setGeometry(QtCore.QRect(30, 320, 81, 61))
        self.b0_5.setIconSize(QtCore.QSize(55, 55))
        self.b0_5.setObjectName(_fromUtf8("b0_5"))
        self.b4_5 = QtGui.QPushButton(Dialog)
        self.b4_5.setGeometry(QtCore.QRect(390, 320, 81, 61))
        self.b4_5.setIconSize(QtCore.QSize(55, 55))
        self.b4_5.setObjectName(_fromUtf8("b4_5"))
        self.b7_3 = QtGui.QPushButton(Dialog)
        self.b7_3.setGeometry(QtCore.QRect(660, 200, 81, 61))
        self.b7_3.setIconSize(QtCore.QSize(55, 55))
        self.b7_3.setObjectName(_fromUtf8("b7_3"))
        self.b2_4 = QtGui.QPushButton(Dialog)
        self.b2_4.setGeometry(QtCore.QRect(210, 260, 81, 61))
        self.b2_4.setIconSize(QtCore.QSize(55, 55))
        self.b2_4.setText(_fromUtf8(""))
        self.b2_4.setObjectName(_fromUtf8("b2_4"))
        self.b6_4 = QtGui.QPushButton(Dialog)
        self.b6_4.setGeometry(QtCore.QRect(570, 260, 81, 61))
        self.b6_4.setIconSize(QtCore.QSize(55, 55))
        self.b6_4.setText(_fromUtf8(""))
        self.b6_4.setObjectName(_fromUtf8("b6_4"))
        self.b5_5 = QtGui.QPushButton(Dialog)
        self.b5_5.setGeometry(QtCore.QRect(480, 320, 81, 61))
        self.b5_5.setIconSize(QtCore.QSize(55, 55))
        self.b5_5.setObjectName(_fromUtf8("b5_5"))
        self.b5_3 = QtGui.QPushButton(Dialog)
        self.b5_3.setGeometry(QtCore.QRect(480, 200, 81, 61))
        self.b5_3.setIconSize(QtCore.QSize(55, 55))
        self.b5_3.setText(_fromUtf8(""))
        self.b5_3.setObjectName(_fromUtf8("b5_3"))
        self.label = QtGui.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(105, 20, 16, 361))
        self.label.setText(_fromUtf8(""))
        self.label.setPixmap(QtGui.QPixmap(_fromUtf8("Img Linja/palito.png")))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(195, 20, 16, 361))
        self.label_2.setText(_fromUtf8(""))
        self.label_2.setPixmap(QtGui.QPixmap(_fromUtf8("Img Linja/palito.png")))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(285, 20, 16, 361))
        self.label_3.setText(_fromUtf8(""))
        self.label_3.setPixmap(QtGui.QPixmap(_fromUtf8("Img Linja/palito.png")))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(375, 20, 16, 361))
        self.label_4.setText(_fromUtf8(""))
        self.label_4.setPixmap(QtGui.QPixmap(_fromUtf8("Img Linja/palito.png")))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(465, 20, 16, 361))
        self.label_5.setText(_fromUtf8(""))
        self.label_5.setPixmap(QtGui.QPixmap(_fromUtf8("Img Linja/palito.png")))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(555, 20, 16, 361))
        self.label_6.setText(_fromUtf8(""))
        self.label_6.setPixmap(QtGui.QPixmap(_fromUtf8("Img Linja/palito.png")))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(645, 20, 16, 361))
        self.label_7.setText(_fromUtf8(""))
        self.label_7.setPixmap(QtGui.QPixmap(_fromUtf8("Img Linja/palito.png")))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.fondo = QtGui.QLabel(Dialog)
        self.fondo.setGeometry(QtCore.QRect(0, 0, 771, 511))
        self.fondo.setText(_fromUtf8(""))
        self.fondo.setPixmap(QtGui.QPixmap(_fromUtf8("Img Linja/fondo.jpg")))
        self.fondo.setObjectName(_fromUtf8("fondo"))
        self.fondo.raise_()
        self.leerArchivoDeTexto.raise_()
        self.salir.raise_()
        self.b0_0.raise_()
        self.b1_0.raise_()
        self.b2_0.raise_()
        self.b3_0.raise_()
        self.b4_0.raise_()
        self.b5_0.raise_()
        self.b7_0.raise_()
        self.b6_0.raise_()
        self.b7_1.raise_()
        self.b4_1.raise_()
        self.b1_1.raise_()
        self.b5_1.raise_()
        self.b6_1.raise_()
        self.b0_1.raise_()
        self.b2_1.raise_()
        self.b3_1.raise_()
        self.b7_2.raise_()
        self.b4_2.raise_()
        self.b1_2.raise_()
        self.b5_2.raise_()
        self.b6_2.raise_()
        self.b0_2.raise_()
        self.b2_2.raise_()
        self.b3_2.raise_()
        self.b1_3.raise_()
        self.b4_4.raise_()
        self.b4_3.raise_()
        self.b1_4.raise_()
        self.b6_3.raise_()
        self.b3_5.raise_()
        self.b3_3.raise_()
        self.b0_3.raise_()
        self.b2_5.raise_()
        self.b2_3.raise_()
        self.b6_5.raise_()
        self.b0_4.raise_()
        self.b7_5.raise_()
        self.b7_4.raise_()
        self.b3_4.raise_()
        self.b1_5.raise_()
        self.b5_4.raise_()
        self.b0_5.raise_()
        self.b4_5.raise_()
        self.b7_3.raise_()
        self.b2_4.raise_()
        self.b6_4.raise_()
        self.b5_5.raise_()
        self.b5_3.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_7.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.leerArchivoDeTexto.setText(_translate("Dialog", "Leer Archivo de Texto", None))
        self.salir.setText(_translate("Dialog", "Salir", None))
        ##self.b0_0.setText(_translate("Dialog", "13", None))
        self.b0_0.setProperty("keyX", _translate("Dialog", "0", None))
        self.b0_0.setProperty("keyY", _translate("Dialog", "0", None))
        #self.b1_0.setText(_translate("Dialog", "1", None))
        #self.b2_0.setText(_translate("Dialog", "2", None))
        #self.b3_0.setText(_translate("Dialog", "3", None))
        #self.b4_0.setText(_translate("Dialog", "4", None))
        #self.b5_0.setText(_translate("Dialog", "5", None))
        #self.b7_0.setText(_translate("Dialog", "7", None))
        #self.b6_0.setText(_translate("Dialog", "6", None))
        #self.b7_1.setText(_translate("Dialog", "8", None))
        #self.b0_1.setText(_translate("Dialog", "14", None))
        #self.b7_2.setText(_translate("Dialog", "9", None))
        #self.b0_2.setText(_translate("Dialog", "15", None))
        #self.b3_5.setText(_translate("Dialog", "21", None))
        #self.b0_3.setText(_translate("Dialog", "16", None))
        #self.b2_5.setText(_translate("Dialog", "20", None))
        #self.b6_5.setText(_translate("Dialog", "24", None))
        #self.b0_4.setText(_translate("Dialog", "17", None))
        #self.b7_5.setText(_translate("Dialog", "12", None))
        #self.b7_4.setText(_translate("Dialog", "11", None))
        #self.b1_5.setText(_translate("Dialog", "19", None))
        #self.b0_5.setText(_translate("Dialog", "18", None))
        #self.b4_5.setText(_translate("Dialog", "22", None))
        #self.b7_3.setText(_translate("Dialog", "10", None))
        #self.b5_5.setText(_translate("Dialog", "23", None))

